### ISSUE TITLE
Website: cadCAD site update to include cadCAD_Edu MOOC

### ISSUE THREAD

**Issue by Jeff-Emmett** [cadCAD-org/Working-Groups#10]
## 📋   Anything to add?
Add a prominent link to the cadCAD Edu course (cadcad.education) to the landing page of cadCAD.org

## 🎉   Subtasks

- [x] Identify asset owner (Jeff can help with this)
- [ ] Decide where link/button need to go
- [ ] Publish site change

## 🤼‍♂️   Reviewer

@Jeff-Emmett

**Comment by Jeff-Emmett** [comment]
Update #1

**Comment by Jeff-Emmett** [comment]
This has been included on a list for a more general website refresh. Closing this issue out.
