### ISSUE TITLE
cadCAD sourcecred [Infra/Admin] [Urgency: Low] [Importance: High]

### ISSUE THREAD

**Issue by seichris** [cadCAD-org/Working-Groups#15]
## 📋 Anything to add?

Reinitialized cadCAD sourcecred using the updated version of sourcecred

## 🎉 Subtasks

- [ ] 
- [ ] 

## 🤼‍♂️ Reviewer, Reported By

@tyler @zargham

## 🔗 Work doc - inspirational links

--

## 🔧 Status

Not started. Ready to be picked up :)

## 👷 Skills

git, access control configurations, github actions, edit json, and minor interactions with a custom app built in js

**Comment by mateodaza** [comment]
So, I checked the instance and it's really really old. SourceCred it's a complete new thing now. 

Did you guys ever make a distribution? 
If not it's better to fork from the new template and we start over from there.
If we want to keep that old data it can be a lot trickier but I can ask one of the main devs there and get help.

Let me know what you guys think 😄

**Comment by mzargham** [comment]
We never used it in any official capacity. Just for some social kudos to early contributors. Its fine to deprecate the old version and deploy something up-to-date.

**Comment by rogervs** [comment]
Source cred has two components (broadly speaking), Cred and Grain.
Cred builds up when you do things for the community, and basically the more Cred you have, the wider the mouth of your bucket is. Cred is not considered an Asset, and all users automatically receive Cred.
Grain on the other hand can be considered an Asset, and users need to opt in to receive Grain. Grain does not need to be used in a community if the community merely wants to keep track of who contributed what. Grain can be used to distribute funds within the community. Grain can be thought of as rain, and the wider your bucket is (due to you having more Cred), the more grain you can catch.

@Jeff-Emmett First question , is the intended use of SourceCred to distribute funds within the community, or merely for reputation points?

**Comment by rogervs** [comment]
# Discord Channel Structure to support SourceCred

SourceCred uses two additional channels in Discord to manage dishing out Creds to users:
* #didathing
* #props

 ## #didathing channel
 * Every time you complete an action that is valuable to the community, but is not on Discource or GitHub, post on #didathing describing what you accomplished.
 * Tag any other contributors
 * Link any useful artefacts and notes
 * The posting itself does not mint the cred, but the emoji reactions to it mint the cred.
 
## #props channel
* Compliment to #didathing, but for what someone else did, which you know wont be seen by the algorithm.
* Describe what they did, tag them in the message, other community members can then mint cred with emoji reactions.
* Eg is when some one helps you in a private DM, afterwards you might post to #props saying "Props to @LBS for explaining the various SourceCred channels to me!"

This is optional, but it seems like a good workflow. Should we implement this? @Jeff-Emmett

**Comment by rogervs** [comment]
# Github Bot Access (Read Only)
@Jeff-Emmett I need an access token for the cadCAD repo ( Only for https://github.com/cadCAD-org/cadCAD at this point).
The key should be read-only without any special scopes or permissions
[Github Tokens](https://github.com/settings/tokens)

**Comment by rogervs** [comment]
# Discord Bot
A bot needs to be added to the discord server to allow sourceCred to access the required information. 
This needs to be done by someone with admin rights on the server.

## The following is needed / needs to be done:
- [x] Get Server ID ( 722946313775480845 ) 
- [x] Create Discord Application (Admin Priv Req) https://sourcecred.io/docs/beta/plugins/discord/#3-create-discord-application
- [x] Create Bot (Admin Priv Req ) https://sourcecred.io/docs/beta/plugins/discord/#4-create-bot
- [x] TOKEN for Bot ( Needs to remain secret - @rogervs needs this )
- [x] Invite Bot to Server (Admin Priv Req ) https://sourcecred.io/docs/beta/plugins/discord/#5-invite-bot-to-server

@Jeff-Emmett

**Comment by Jeff-Emmett** [comment]
Summary of our discussion today in the WG call:

1. We'll start off with cred and see about integrating grain later.
2. We'll keep cadCAD Discord channel structure as it is for the time being, and break out #didathing and #props at a point when we find those posts distracting from general conversation.
3. Github Bot access token has been granted for next steps.
4. @seichris is on the Discord bot integration for sourcecred.

Thanks for moving this forward @rogervs, looking forward to next steps in our next call!

**Comment by Jeff-Emmett** [comment]
- Decided last week to focus just on Github for starters for simplification of available levers. Discourse could be next, followed by Discord. 
- Want to be careful about emoji's in discord exacerbating attention hacking and the 'instagram effect'

- Jeff to follow up with TEC on Sourcecred parameters chosen
- Roger sharing instructions to check out the cadCAD SourceCred for early cadCAD stakeholders
- Possibility to invite someone from sourcecred to speak at a future call as to best lessons learned from other community deployments

**Comment by Jeff-Emmett** [comment]
- Roger is waiting on weights for SC
- TEC as example?  Jeff to find parameter weighting they used
- Upgrade to suggest to Sourcecred: submitting **jupyter notebooks** (in particular) to github includes data, can look like massive amounts of work (since data input looks like line inputs)
- QA processes on scores assigned (e.g. should Roger's score be higher than Ben's score?)
- Coordinate with a few different communities to determine best practices & next steps (Jeff to determine who may be available to chat!)
-
