### ISSUE TITLE
Discord: Telegram bridge to cadCAD channel

### ISSUE THREAD

**Issue by seichris** [cadCAD-org/Working-Groups#18]
## 📋 Anything to add?
Bridge all the discord channels! =)

(old: cadCAD TG channel with cadCAD discord channel (create on discord))

## 🎉 Subtasks

- [x] Jeff to give appropriate discord permissions
- [x] Bring in Kay (geeleeroyale) if needed
- [x] Set up dedicated discord channel (or direct to general channel)
- [x] Set up bot

## 🤼‍♂️ Reviewer, Reported By

@Catoya @Jeff-Emmett 

## 🔗 Work doc - inspirational links

https://docs.google.com/document/d/1ZyqgIxM1dqk3CXJtUicW3Q9lYhRiqZ2CX7nGshoCO3I/edit#

## 🔧 Status

--

## 👷 Skills

--

**Comment by Jeff-Emmett** [comment]
Hey @seichris & @DrCatman - I gave you both access in the cadCAD discord for server & webhook management for bots - let me know if there are any next steps I can help with on this.  Kay is also able to be pulled in on this task if needed - let me know if I can help with intros etc.

**Comment by seichris** [comment]
Channel bridging overview https://docs.google.com/document/d/1ZyqgIxM1dqk3CXJtUicW3Q9lYhRiqZ2CX7nGshoCO3I/edit

**Comment by Jeff-Emmett** [comment]
Thanks so much for grinding on this @seichris @DrCatman, telegram integrations look great!
